### ISSUE TITLE
Exception processing template "login": Error resolving template "login",

### ISSUE THREAD

**Issue by changman** [hendisantika/spring-boot-adminlte#1]
hi

I packaged this project by maven in windows 10.
and copied the jar file(spring-adminlte2-0.0.1-SNAPSHOT.jar) in target folder to a deploy folder.
and ran java -jar spring-adminlte2-0.0.1-SNAPSHOT.jar.
and connect http://localhost:8080 by chrome.
and met this error page. 

"
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Feb 23 12:57:13 KST 2019
There was an unexpected error (type=Internal Server Error, status=500).
Error resolving template "login", template might not exist or might not be accessible by any of the configured Template Resolvers
"

**Comment by hendisantika** [comment]
Is it already solved @changman ?

**Comment by changman** [comment]
@hendisantika I tested in my desktop environment windows 10

**Comment by hendisantika** [comment]
OK. I will close the issue then.
