### ISSUE TITLE
how to connect database? 

### ISSUE THREAD

**Issue by sokvebolkol** [hendisantika/spring-boot-adminlte#10]
I have configured like : 
![image](https://user-images.githubusercontent.com/44717892/78256864-4b8c1c00-7523-11ea-91e9-123542a49c09.png)

But I got a lot of error in the console

**Comment by hendisantika** [comment]
What's the error?
Can You show me the error?

**Comment by sokvebolkol** [comment]
I think the error from the database connection. And here is my error: 
![image](https://user-images.githubusercontent.com/44717892/78322380-c5aab800-7598-11ea-8313-ff66f224010e.png)

Thank you:)

**Comment by hendisantika** [comment]
Set your own mysql password first.

**Comment by hendisantika** [comment]
So, its already fixed ya. I will close this issue then.
