### ISSUE TITLE
ignore my pull request

### ISSUE THREAD

**Issue by vinnyparker** [hendisantika/spring-boot-adminlte#13]
Hi! I just forked your project. Thats amazing. thanx a lot.
I'm studing so I'm goint to migrate to lastest versions of the enviroments, java, spring boot. Also migrating to gradle and postgresql.
So I created a branch on my repository to do that. 
Just ignore if apears a pul request here. Thanx a lot again.

**Comment by hendisantika** [comment]
OK. You are welcome @vinnyparker
