### ISSUE TITLE
What License?

### ISSUE THREAD

**Issue by aensley** [hendisantika/spring-boot-adminlte#5]
What license have you given the code in this repository?

**Comment by hendisantika** [comment]
Any issue if I am not put a license @aensley ?

**Comment by hendisantika** [comment]
So, Which license should use for this project @aensley ?

**Comment by aensley** [comment]
@hendisantika As the software owner, that's really up to you. If you want the most open, simple option, I would recommend the MIT license: https://opensource.org/licenses/MIT

It has the least restrictions while still protecting you from liability.

**Comment by hendisantika** [comment]
OK. Then

**Comment by hendisantika** [comment]
MIT LICENSE added. Therefore I close this issue.
