### ISSUE TITLE
Error in service layer

### ISSUE THREAD

**Issue by SaiAvinashP** [hendisantika/spring-boot-adminlte#6]
hi, i'm getting an error like this... can you give me a solution of this error...

  public Page<T> getList(Integer pageNumber) {
        PageRequest pageRequest =
                                    new PageRequest(pageNumber - 1, PAGE_SIZE, Sort.Direction.DESC, "id");
      return getRepository().findAll(pageRequest);
    }
ERROR: The constructor PageRequest(int, int, Sort.Direction, String) is undefined

**Comment by hendisantika** [comment]
I already fixed it.
